### ISSUE TITLE
📝 Doc Improvements based on comments (Milestone 2 Documentation)

### ISSUE THREAD

**Issue by gerteck** [gerteck/SaveLah#20]
### Pain

If we don't meet the requirements later get demoted to the Soviet's Vostok programme. Tough luck.

### Suggested Documentation

- Set up UI/UX and user flow for the user forum feature.
- Analytics: More details are needed about the analytics - how will you track spending habits, what data will you use, algorithms, a technical discussion on how you will code it out, etc.
- The Readme should have have technical details as well: for example, how you will be calculating and updating the summary statistics (are you planning to use microservices here), the API design, database schema, frontend component tree, etc.
- A lot more details need to be given for software engineering practices, it is a very important section. Do refer to the previous years reports/PM me on Telegram.
- Project video is great, poster needs more details but is very clean in its graphics and layout.
- For Readme, in general, more diagrams can be included (for example, frontend component tree, architectural setup, database schema), high-level overview of how the various features will be coded or of intended design patterns, more evidence of software engineering (do not just tell, but paste images and give examples of your sprints)

### Tasks (In general)

- [x] Work on Analytics 
- [x] Work on ReadMe
- [x] Work on Poster
- [x] Work on Video

Thanks!
