### ISSUE TITLE
✨Add a full spending report page

### ISSUE THREAD

**Issue by CJerrong** [gerteck/SaveLah#48]
**Is your feature request related to a problem? Please describe.**
### Pain or Motivation

A full spending report component for more in depth analysis of spending

### Suggested Solution

Implement a separate Tab screen for full report, where reports are generated for each month, in a scrollable tab view

### Tasks

- [x] Create base for scrollable tab view
- [x] Create templates for full spending reports
- [x] Implement analysis tools, pie charts, bar graphs, previous month comparisons

### Screenshots

Thanks!
