### ISSUE TITLE
✨Add Category icons

### ISSUE THREAD

**Issue by CJerrong** [gerteck/SaveLah#81]
**Is your feature request related to a problem? Please describe.**
### Pain or Motivation

We need category icons for add transaction as well as when displaying transaction

### Suggested Solution

Store icons locally, use an index to link to icons

### Tasks

- [x] Collate icons
- [x] Have a mapping function to map from index to icons
- [x] Implement firestore storage and query of categories
- [x] Integrate into add transaction
- [x] Integrate into transaction history
- [x] Integrate into home page
- [x] Implement add category screen
- [x] Integrate into edit transaction
- [ ] Integrate into spending report

### Screenshots

Thanks!
