### ISSUE TITLE
✨ Additional Features 

### ISSUE THREAD

**Issue by gerteck** [gerteck/SaveLah#89]
**Is your feature request related to a problem? Please describe.**
Additional Extensions to the current application if time permits:

### Tasks

- [x] Add All Posts Page of a User
- [x] Adding Overall Balance functionality 
- [ ] Add New Categories for Posts

Thanks!
